[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "my-better-isabelle-prover"
version = "0.1.0"
description = "Patch manager for Isabelle installations"
requires-python = ">=3.12"
license = "LGPL-2.1-or-later"
authors = [
    { name = "Qiyuan Xu", email = "xu@qiyuan.me" },
]
dependencies = []

[project.scripts]
my-better-isabelle = "my_better_isabelle_prover.cli:main"

[tool.setuptools.packages.find]
include = ["my_better_isabelle_prover", "my_better_isabelle_prover.*"]

[tool.setuptools.package-data]
my_better_isabelle_prover = ["patches/**/*.patch"]
